name: pos_mobile
description: "Sleek POS - Mobile Point of Sale System"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.7
  firebase_crashlytics: ^4.3.2

  # Auth & Security
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3

  # State Management
  provider: ^6.1.5

  # Routing
  go_router: ^14.8.1

  # UI
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  lucide_icons: ^0.257.0

  # Utilities
  intl: any
  mailer: ^7.1.0
  blue_thermal_printer: ^1.2.3
  esc_pos_utils_plus: ^2.0.3
  barcode_scan2: ^4.4.0
  pdf: ^3.11.1
  printing: ^5.13.3
  excel: ^4.0.6
  path_provider: ^2.1.5
  open_file: ^3.5.7
  share_plus: ^10.1.4
  mobile_scanner: ^7.2.0
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
